/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gps_msg implements lcm.lcm.LCMEncodable
{
    public double time;
    public double latitude;
    public double longitude;
    public double altitude;
    public double utm_x;
    public double utm_y;
    public byte utm_zone;
    public String utm_zone_letter;
 
    public gps_msg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd5df6f0686a68b50L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.gps_msg.class))
            return 0L;
 
        classes.add(exlcm.gps_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeDouble(this.time); 
 
        outs.writeDouble(this.latitude); 
 
        outs.writeDouble(this.longitude); 
 
        outs.writeDouble(this.altitude); 
 
        outs.writeDouble(this.utm_x); 
 
        outs.writeDouble(this.utm_y); 
 
        outs.writeByte(this.utm_zone); 
 
        __strbuf = new char[this.utm_zone_letter.length()]; this.utm_zone_letter.getChars(0, this.utm_zone_letter.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public gps_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gps_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.gps_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.gps_msg o = new exlcm.gps_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.time = ins.readDouble();
 
        this.latitude = ins.readDouble();
 
        this.longitude = ins.readDouble();
 
        this.altitude = ins.readDouble();
 
        this.utm_x = ins.readDouble();
 
        this.utm_y = ins.readDouble();
 
        this.utm_zone = ins.readByte();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.utm_zone_letter = new String(__strbuf);
 
    }
 
    public exlcm.gps_msg copy()
    {
        exlcm.gps_msg outobj = new exlcm.gps_msg();
        outobj.time = this.time;
 
        outobj.latitude = this.latitude;
 
        outobj.longitude = this.longitude;
 
        outobj.altitude = this.altitude;
 
        outobj.utm_x = this.utm_x;
 
        outobj.utm_y = this.utm_y;
 
        outobj.utm_zone = this.utm_zone;
 
        outobj.utm_zone_letter = this.utm_zone_letter;
 
        return outobj;
    }
 
}

