"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gps_msg(object):
    __slots__ = ["time", "latitude", "longitude", "altitude", "utm_x", "utm_y", "utm_zone", "utm_zone_letter"]

    def __init__(self):
        self.time = 0.0
        self.latitude = 0.0
        self.longitude = 0.0
        self.altitude = 0.0
        self.utm_x = 0.0
        self.utm_y = 0.0
        self.utm_zone = 0
        self.utm_zone_letter = ""

    def encode(self):
        buf = BytesIO()
        buf.write(gps_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddddddb", self.time, self.latitude, self.longitude, self.altitude, self.utm_x, self.utm_y, self.utm_zone))
        __utm_zone_letter_encoded = self.utm_zone_letter.encode('utf-8')
        buf.write(struct.pack('>I', len(__utm_zone_letter_encoded)+1))
        buf.write(__utm_zone_letter_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps_msg()
        self.time, self.latitude, self.longitude, self.altitude, self.utm_x, self.utm_y, self.utm_zone = struct.unpack(">ddddddb", buf.read(49))
        __utm_zone_letter_len = struct.unpack('>I', buf.read(4))[0]
        self.utm_zone_letter = buf.read(__utm_zone_letter_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps_msg in parents: return 0
        tmphash = (0xd5df6f0686a68b50) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps_msg._packed_fingerprint is None:
            gps_msg._packed_fingerprint = struct.pack(">Q", gps_msg._get_hash_recursive([]))
        return gps_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

