// Generated by gencpp from file hw02/AddThreeIntsRequest.msg
// DO NOT EDIT!


#ifndef HW02_MESSAGE_ADDTHREEINTSREQUEST_H
#define HW02_MESSAGE_ADDTHREEINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw02
{
template <class ContainerAllocator>
struct AddThreeIntsRequest_
{
  typedef AddThreeIntsRequest_<ContainerAllocator> Type;

  AddThreeIntsRequest_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  AddThreeIntsRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::hw02::AddThreeIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw02::AddThreeIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddThreeIntsRequest_

typedef ::hw02::AddThreeIntsRequest_<std::allocator<void> > AddThreeIntsRequest;

typedef boost::shared_ptr< ::hw02::AddThreeIntsRequest > AddThreeIntsRequestPtr;
typedef boost::shared_ptr< ::hw02::AddThreeIntsRequest const> AddThreeIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw02::AddThreeIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hw02

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hw02': ['/home/paul/catkin_ws/src/hw02/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw02::AddThreeIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw02::AddThreeIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw02::AddThreeIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95da2541c9d6989c0876f480a9b1c7e4";
  }

  static const char* value(const ::hw02::AddThreeIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95da2541c9d6989cULL;
  static const uint64_t static_value2 = 0x0876f480a9b1c7e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw02/AddThreeIntsRequest";
  }

  static const char* value(const ::hw02::AddThreeIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
int64 z\n\
";
  }

  static const char* value(const ::hw02::AddThreeIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddThreeIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw02::AddThreeIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw02::AddThreeIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW02_MESSAGE_ADDTHREEINTSREQUEST_H
