// Generated by gencpp from file hw02/AddThreeInts.msg
// DO NOT EDIT!


#ifndef HW02_MESSAGE_ADDTHREEINTS_H
#define HW02_MESSAGE_ADDTHREEINTS_H

#include <ros/service_traits.h>


#include <hw02/AddThreeIntsRequest.h>
#include <hw02/AddThreeIntsResponse.h>


namespace hw02
{

struct AddThreeInts
{

typedef AddThreeIntsRequest Request;
typedef AddThreeIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddThreeInts
} // namespace hw02


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw02::AddThreeInts > {
  static const char* value()
  {
    return "53028d7f0cdbf27905a5df65392f9c8b";
  }

  static const char* value(const ::hw02::AddThreeInts&) { return value(); }
};

template<>
struct DataType< ::hw02::AddThreeInts > {
  static const char* value()
  {
    return "hw02/AddThreeInts";
  }

  static const char* value(const ::hw02::AddThreeInts&) { return value(); }
};


// service_traits::MD5Sum< ::hw02::AddThreeIntsRequest> should match 
// service_traits::MD5Sum< ::hw02::AddThreeInts > 
template<>
struct MD5Sum< ::hw02::AddThreeIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw02::AddThreeInts >::value();
  }
  static const char* value(const ::hw02::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw02::AddThreeIntsRequest> should match 
// service_traits::DataType< ::hw02::AddThreeInts > 
template<>
struct DataType< ::hw02::AddThreeIntsRequest>
{
  static const char* value()
  {
    return DataType< ::hw02::AddThreeInts >::value();
  }
  static const char* value(const ::hw02::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw02::AddThreeIntsResponse> should match 
// service_traits::MD5Sum< ::hw02::AddThreeInts > 
template<>
struct MD5Sum< ::hw02::AddThreeIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw02::AddThreeInts >::value();
  }
  static const char* value(const ::hw02::AddThreeIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw02::AddThreeIntsResponse> should match 
// service_traits::DataType< ::hw02::AddThreeInts > 
template<>
struct DataType< ::hw02::AddThreeIntsResponse>
{
  static const char* value()
  {
    return DataType< ::hw02::AddThreeInts >::value();
  }
  static const char* value(const ::hw02::AddThreeIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW02_MESSAGE_ADDTHREEINTS_H
